name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_JSON_KEY }}
          access_token_lifetime: 300s

      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCP_ARTIFACT_REPOSITORY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}


      # - name: Build Docker image
        # run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld .

      # - name: Push Docker image to Google Cloud Registry
        # run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld

      - name: Deploy to Cloud Run
        run: gcloud run deploy my-service --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld --platform=managed --region=us-central1
