name: Deploy quantm

on:
  workflow_dispatch:
    inputs:
      commits_data:
        description: "Base64-encoded JSON-encoded commits data"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode and Unmarshal JSON data
        run: |
          # Decode Base64 and store in a variable
          JSON_DATA=$(echo "${{ inputs.commits_data }}" | base64 --decode)

          # Unmarshal JSON into an environment variable
          export COMMITS_DATA_JSON="$JSON_DATA"

          # Print unmarshaled JSON data
          echo "Unmarshaled Commits Data:"
          echo "$COMMITS_DATA_JSON"

          # If needed, you can use jq to pretty-print the JSON
          echo "$COMMITS_DATA_JSON" | jq '.'

      - name: Use the unmarshaled data
        run: |
          # Now you can use the unmarshaled data as needed in your workflow steps
