name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Authenticate to Google Cloud Registry
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld .

      - name: Push Docker image to Google Cloud Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld

      - name: Deploy to Cloud Run
        run: gcloud run deploy my-service --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ctrlplane/helloworld --platform=managed --region=us-central1
